services:
  tasks: # Имя и адрес сервиса, следует обратить внимание как оно используется на 40 строчке
    image: myimage # Версия образа приложения
    build: .
    networks:
      - proxy
    volumes:
      # Путь к БД
      - "./src/test.db:/app/test.db"
    environment:
      PORT: 8080 # Меняем порт на удобный для нас

  nginx:
    # ‼️ При работе в закрытом контуре МГТУ использовать образ registry.gitlab.bmstu.ru/devops-dataops-intro/labs/lab-2-docker/nginx
    image: nginx
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - proxy
    configs:
      - source: nginx-default
        target: /etc/nginx/templates/conf.d/default.conf.template
    secrets:
      - source: cert-pem
        target: cert.pem
      - source: key-pem
        target: key.pem
    environment:
      TZ: Europe/Moscow
      SERVER_NAME: localhost

      SSL_CERT: "/run/secrets/cert.pem"
      SSL_CERT_KEY: "/run/secrets/key.pem"

      NGINX_ENVSUBST_TEMPLATE_DIR: "/etc/nginx/templates"
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".template"
      NGINX_ENVSUBST_OUTPUT_DIR: "/etc/nginx"

      # Адрес обращения к сервису
      PASS: http://tasks:8000

configs:
  nginx-default:
    file: ./nginx-default.template.config

secrets:
  cert-pem:
    file: ./cert.pem
  key-pem:
    file: ./key.pem

networks:
  proxy:
