services:
  tasks:
    image: myimage
    build: .
    networks:
      - proxy
    volumes:
      - "./src/test.db:/app/test.db"
    environment:
      PORT: 8080

  nginx:
    image: nginx
    ports:
      - 80
      - 443
    networks:
      - proxy
    configs:
      - source: nginx-default
        target: /etc/nginx/templates/conf.d/default.conf.template
    secrets:
      - source: cert-pem
        target: cert.pem
      - source: key-pem
        target: key.pem
    environment:
      TZ: Europe/Moscow
      SERVER_NAME: localhost

      SSL_CERT:     "/run/secrets/cert.pem"
      SSL_CERT_KEY: "/run/secrets/key.pem"

      NGINX_ENVSUBST_TEMPLATE_DIR:    "/etc/nginx/templates"
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".template"
      NGINX_ENVSUBST_OUTPUT_DIR:      "/etc/nginx"

      PASS: http://tasks:8000

configs:
  nginx-default:
    file: ./nginx-default.template.config

secrets:
  cert-pem:
    file: ./cert.pem
  key-pem:
    file: ./key.pem

networks:
  proxy:
